"""empty message

Revision ID: 3c1bdf2a174a
Revises: 2eb81e46ebd3
Create Date: 2025-01-10 15:08:31.817905

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '3c1bdf2a174a'
down_revision: Union[str, None] = '2eb81e46ebd3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('review', 'rating',
               existing_type=mysql.FLOAT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('review', 'rating',
               existing_type=mysql.FLOAT(),
               nullable=False)
    # ### end Alembic commands ###
