"""UserBlock 추가

Revision ID: 9ba2b464e78f
Revises: 2067eeb29d39
Create Date: 2025-01-25 23:53:44.971210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ba2b464e78f'
down_revision: Union[str, None] = '2067eeb29d39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('review_ibfk_1', 'review', type_='foreignkey')
    op.drop_constraint('review_ibfk_2', 'review', type_='foreignkey')
    op.create_foreign_key(None, 'review', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'review', 'movie', ['movie_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('user_likes_comment_ibfk_2', 'user_likes_comment', type_='foreignkey')
    op.drop_constraint('user_likes_comment_ibfk_1', 'user_likes_comment', type_='foreignkey')
    op.create_foreign_key(None, 'user_likes_comment', 'comment', ['comment_id'], ['id'])
    op.create_foreign_key(None, 'user_likes_comment', 'user', ['user_id'], ['id'])
    op.drop_constraint('user_likes_review_ibfk_1', 'user_likes_review', type_='foreignkey')
    op.drop_constraint('user_likes_review_ibfk_2', 'user_likes_review', type_='foreignkey')
    op.create_foreign_key(None, 'user_likes_review', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'user_likes_review', 'review', ['review_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_likes_review', type_='foreignkey')
    op.drop_constraint(None, 'user_likes_review', type_='foreignkey')
    op.create_foreign_key('user_likes_review_ibfk_2', 'user_likes_review', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('user_likes_review_ibfk_1', 'user_likes_review', 'review', ['review_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'user_likes_comment', type_='foreignkey')
    op.drop_constraint(None, 'user_likes_comment', type_='foreignkey')
    op.create_foreign_key('user_likes_comment_ibfk_1', 'user_likes_comment', 'comment', ['comment_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('user_likes_comment_ibfk_2', 'user_likes_comment', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'review', type_='foreignkey')
    op.drop_constraint(None, 'review', type_='foreignkey')
    op.create_foreign_key('review_ibfk_2', 'review', 'user', ['user_id'], ['id'])
    op.create_foreign_key('review_ibfk_1', 'review', 'movie', ['movie_id'], ['id'])
    # ### end Alembic commands ###
