"""add view_date in review

Revision ID: be8a2fa6f058
Revises: 56b0a26e0de1
Create Date: 2025-01-31 23:44:45.374968

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be8a2fa6f058'
down_revision: Union[str, None] = '56b0a26e0de1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review', sa.Column('view_date', sa.JSON(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('review', 'view_date')
    # ### end Alembic commands ###
