"""participant like_count

Revision ID: 22af0add3b7c
Revises: 5e962e6ec768
Create Date: 2025-01-29 23:57:46.875723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22af0add3b7c'
down_revision: Union[str, None] = '5e962e6ec768'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_likes_participant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('participant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['participant_id'], ['participant.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('participant', sa.Column('like_count', sa.Integer(), nullable=False))
    op.add_column('participant', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'participant', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'participant', type_='foreignkey')
    op.drop_column('participant', 'user_id')
    op.drop_column('participant', 'like_count')
    op.drop_table('user_likes_participant')
    # ### end Alembic commands ###
