"""add status_message column

Revision ID: d6a643d1533a
Revises: f11b9b212861
Create Date: 2025-01-17 00:36:59.026038

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6a643d1533a'
down_revision: Union[str, None] = 'f11b9b212861'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('status_message', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'status_message')
    # ### end Alembic commands ###
