"""fix collection

Revision ID: 65dc72edb8c5
Revises: e9b6097534f2
Create Date: 2025-01-14 15:09:19.113423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65dc72edb8c5'
down_revision: Union[str, None] = 'e9b6097534f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('collection_ibfk_1', 'collection', type_='foreignkey')
    op.create_foreign_key(None, 'collection', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('collection_comment_ibfk_2', 'collection_comment', type_='foreignkey')
    op.drop_constraint('collection_comment_ibfk_1', 'collection_comment', type_='foreignkey')
    op.create_foreign_key(None, 'collection_comment', 'collection', ['collection_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'collection_comment', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('movie_collection_ibfk_2', 'movie_collection', type_='foreignkey')
    op.drop_constraint('movie_collection_ibfk_1', 'movie_collection', type_='foreignkey')
    op.create_foreign_key(None, 'movie_collection', 'collection', ['collection_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'movie_collection', 'movie', ['movie_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('user_likes_collection_comment_ibfk_1', 'user_likes_collection_comment', type_='foreignkey')
    op.drop_constraint('user_likes_collection_comment_ibfk_2', 'user_likes_collection_comment', type_='foreignkey')
    op.create_foreign_key(None, 'user_likes_collection_comment', 'collection_comment', ['collection_comment_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_likes_collection_comment', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_likes_collection_comment', type_='foreignkey')
    op.drop_constraint(None, 'user_likes_collection_comment', type_='foreignkey')
    op.create_foreign_key('user_likes_collection_comment_ibfk_2', 'user_likes_collection_comment', 'user', ['user_id'], ['id'])
    op.create_foreign_key('user_likes_collection_comment_ibfk_1', 'user_likes_collection_comment', 'collection_comment', ['collection_comment_id'], ['id'])
    op.drop_constraint(None, 'movie_collection', type_='foreignkey')
    op.drop_constraint(None, 'movie_collection', type_='foreignkey')
    op.create_foreign_key('movie_collection_ibfk_1', 'movie_collection', 'collection', ['collection_id'], ['id'])
    op.create_foreign_key('movie_collection_ibfk_2', 'movie_collection', 'movie', ['movie_id'], ['id'])
    op.drop_constraint(None, 'collection_comment', type_='foreignkey')
    op.drop_constraint(None, 'collection_comment', type_='foreignkey')
    op.create_foreign_key('collection_comment_ibfk_1', 'collection_comment', 'collection', ['collection_id'], ['id'])
    op.create_foreign_key('collection_comment_ibfk_2', 'collection_comment', 'user', ['user_id'], ['id'])
    op.drop_constraint(None, 'collection', type_='foreignkey')
    op.create_foreign_key('collection_ibfk_1', 'collection', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
