"""empty message

Revision ID: 2eb81e46ebd3
Revises: f2d47c4d0eb0
Create Date: 2025-01-10 14:46:58.894464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2eb81e46ebd3'
down_revision: Union[str, None] = 'f2d47c4d0eb0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('review', 'content',
               existing_type=mysql.VARCHAR(length=500),
               nullable=True)
    op.alter_column('review', 'status',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('review', 'status',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
    op.alter_column('review', 'content',
               existing_type=mysql.VARCHAR(length=500),
               nullable=False)
    # ### end Alembic commands ###
