"""test

Revision ID: 84b0d6c1b6dd
Revises: 1c08eda11ea3
Create Date: 2025-01-31 17:28:32.463923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '84b0d6c1b6dd'
down_revision: Union[str, None] = '1c08eda11ea3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('user_id', table_name='user_rating')
    op.drop_table('user_rating')
    op.drop_index('user_id', table_name='user_preference')
    op.drop_table('user_preference')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_preference',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('actor_dict', mysql.JSON(), nullable=True),
    sa.Column('director_dict', mysql.JSON(), nullable=True),
    sa.Column('country_dict', mysql.JSON(), nullable=True),
    sa.Column('genre_dict', mysql.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='user_preference_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('user_id', 'user_preference', ['user_id'], unique=True)
    op.create_table('user_rating',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('rating_num', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('rating_avg', mysql.FLOAT(), nullable=True),
    sa.Column('rating_dist', mysql.JSON(), nullable=True),
    sa.Column('rating_mode', mysql.FLOAT(), nullable=True),
    sa.Column('rating_message', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('viewing_time', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('viewing_message', mysql.VARCHAR(length=100), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='user_rating_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('user_id', 'user_rating', ['user_id'], unique=True)
    # ### end Alembic commands ###
