"""empty message

Revision ID: d9b77a0521b4
Revises: d6a643d1533a
Create Date: 2025-01-22 09:08:48.068987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9b77a0521b4'
down_revision: Union[str, None] = 'd6a643d1533a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('comment_ibfk_2', 'comment', type_='foreignkey')
    op.drop_constraint('comment_ibfk_1', 'comment', type_='foreignkey')
    op.create_foreign_key(None, 'comment', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'comment', 'review', ['review_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('review_ibfk_1', 'review', type_='foreignkey')
    op.drop_constraint('review_ibfk_2', 'review', type_='foreignkey')
    op.create_foreign_key(None, 'review', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'review', 'movie', ['movie_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'review', type_='foreignkey')
    op.drop_constraint(None, 'review', type_='foreignkey')
    op.create_foreign_key('review_ibfk_2', 'review', 'user', ['user_id'], ['id'])
    op.create_foreign_key('review_ibfk_1', 'review', 'movie', ['movie_id'], ['id'])
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.create_foreign_key('comment_ibfk_1', 'comment', 'review', ['review_id'], ['id'])
    op.create_foreign_key('comment_ibfk_2', 'comment', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
