"""movie running_time nullable

Revision ID: 1b8847f3edf8
Revises: 71a45d95f65c
Create Date: 2025-01-09 15:32:30.649786

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '1b8847f3edf8'
down_revision: Union[str, None] = '71a45d95f65c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('movie', 'running_time',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('movie', 'running_time',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
