"""view_date type변경

Revision ID: 0bb58254c6d7
Revises: fcfe6db92e39
Create Date: 2025-02-01 03:35:40.776972

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0bb58254c6d7'
down_revision: Union[str, None] = 'fcfe6db92e39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('review', 'view_date',
               existing_type=mysql.JSON(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('review', 'view_date',
               existing_type=mysql.JSON(),
               nullable=True)
    # ### end Alembic commands ###
