"""user_preference,rating

Revision ID: f7e9c2dd5358
Revises: 2830bdc6adda
Create Date: 2025-02-01 07:41:58.645274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7e9c2dd5358'
down_revision: Union[str, None] = '2830bdc6adda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_preference',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('actor_dict', sa.JSON(), nullable=True),
    sa.Column('director_dict', sa.JSON(), nullable=True),
    sa.Column('country_dict', sa.JSON(), nullable=True),
    sa.Column('genre_dict', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('user_rating',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('rating_num', sa.Integer(), nullable=False),
    sa.Column('rating_avg', sa.Float(), nullable=True),
    sa.Column('rating_dist', sa.JSON(), nullable=True),
    sa.Column('rating_mode', sa.Float(), nullable=True),
    sa.Column('rating_message', sa.String(length=100), nullable=True),
    sa.Column('viewing_time', sa.Integer(), nullable=True),
    sa.Column('viewing_message', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_rating')
    op.drop_table('user_preference')
    # ### end Alembic commands ###
