"""empty message

Revision ID: f2d47c4d0eb0
Revises: 1b8847f3edf8
Create Date: 2025-01-10 14:37:24.227611

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2d47c4d0eb0'
down_revision: Union[str, None] = '1b8847f3edf8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review', sa.Column('spoiler', sa.Boolean(), nullable=False))
    op.add_column('review', sa.Column('status', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('review', 'status')
    op.drop_column('review', 'spoiler')
    # ### end Alembic commands ###
