"""add user_rating,preference

Revision ID: 1c08eda11ea3
Revises: b2fc27df03b7
Create Date: 2025-01-31 17:22:16.116950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c08eda11ea3'
down_revision: Union[str, None] = 'b2fc27df03b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
